# Generated by Django 3.2.3 on 2021-06-02 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210602_2116'),
        ('article', '0002_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_info', to='author.authorpage'),
        ),
    ]
