# Generated by Django 3.2.3 on 2021-06-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210603_1737'),
        ('article', '0004_articlepage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='head_foot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_foot', to='home.homepage'),
        ),
    ]
